# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c37819a2c85b3ee01bd7b0b4057d46d295782d44adad07438eb4e0afc7cc45384cbbeeb5a34dd2bb35551e0abff3d781bf21c6370233682072f47c4809cd705

test:
  secret_key_base: 806f1b7ee50487d53168f8ae9005df26948614486a9423654d9d2b71387f97113e38cae83d1ff93d3bbf2707478c9bf0402a8b19391f249c68cf34e60fb16adc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
